### ISSUE TITLE
oracle-cloud-agent installation failed due to bucket permissions

### ISSUE THREAD

**Issue by hrvolapeter** [oracle-quickstart/oci-hpc#33]
Hello, the installation of oracle-cloud-agent fails because the bucket url is not accessible to public. 
```
  yum:
    name: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/aV_mSl96KIiapAeZtsyo-SUcPCSurDfWaj06f4XVVoNKIsxvqlZ65guPTnMuNawR/n/imagegen/b/agent_test/o/1.37.0/3/oracle-cloud-agent-1.37.2-10459.el8.x86_64.rpm"
    state: present
    disable_gpg_check: yes
```
```
{"code":"BucketNotFound","message":"Either the bucket named 'agent_test' does not exist in the namespace 'imagegen' or you are not authorized to access it"}
```
